project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  # Docs (Docusaurus)
  - source: /website/docs/**
    translation: /website/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**
    ignore:
      - /website/docs/**/assets/**

  # UI strings (if later added under i18n/<locale>/code.json)
  # - source: /website/i18n/en/code.json
  #   translation: /website/i18n/%two_letters_code%/code.json

