name: Docs

on:
  push:
    branches: [main, master]
    tags: ['v*', 'V*']
  pull_request:
    branches: [main, master]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCSEARCH_APP_ID: ${{ secrets.DOCSEARCH_APP_ID }}
      DOCSEARCH_API_KEY: ${{ secrets.DOCSEARCH_API_KEY }}
      DOCSEARCH_INDEX_NAME: ${{ secrets.DOCSEARCH_INDEX_NAME }}
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: website/package-lock.json
      - name: Install deps
        run: npm ci

      # Build PRs (English only) + preview artifact
      - name: Build (PRs: en only)
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run build -- --locale en
      - name: Link check (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [ ! -f ./build/index.html ]; then echo "No index.html in build — skipping link check"; exit 0; fi
          rm -rf ./build-linkcheck || true
          mkdir -p ./build-linkcheck/Thunderbird-Reply-with-Attachments
          rsync -a --delete --exclude 'Thunderbird-Reply-with-Attachments/**' ./build/ ./build-linkcheck/Thunderbird-Reply-with-Attachments/
          npx --yes http-server ./build-linkcheck -p 5050 -s >/dev/null 2>&1 &
          sleep 2
          npx --yes linkinator "http://127.0.0.1:5050/Thunderbird-Reply-with-Attachments/" --recurse --silent --skip "mailto:|github\.com|bitranox\.github\.io|addons\.thunderbird\.net"
          kill %1 || true
          rm -rf ./build-linkcheck || true
      - name: Upload build artifact (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: docs-preview
          path: website/build
      - name: Docs preview URL
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Preview artifacts: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      # Build on main/tags and upload to Pages
      - name: Configure Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/configure-pages@v5
      - name: Build (main/tags: all locales)
        if: ${{ github.event_name != 'pull_request' }}
        run: npm run build
      - name: Link check (main/tags)
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [ ! -f ./build/index.html ]; then echo "No index.html in build — skipping link check"; exit 0; fi
          rm -rf ./build-linkcheck || true
          mkdir -p ./build-linkcheck/Thunderbird-Reply-with-Attachments
          rsync -a --delete --exclude 'Thunderbird-Reply-with-Attachments/**' ./build/ ./build-linkcheck/Thunderbird-Reply-with-Attachments/
          npx --yes http-server ./build-linkcheck -p 5050 -s >/dev/null 2>&1 &
          sleep 2
          npx --yes linkinator "http://127.0.0.1:5050/Thunderbird-Reply-with-Attachments/" --recurse --silent --skip "mailto:|github\.com|bitranox\.github\.io|addons\.thunderbird\.net"
          kill %1 || true
          rm -rf ./build-linkcheck || true
      - name: Upload Pages artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

