name: Release — Pack Add-on

on:
  push:
    tags:
      - 'v*'
      - 'V*'
  workflow_dispatch: {}

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Build ZIPs (ATN + LOCAL)
        run: make pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rwa-zips-${{ github.ref_name }}
          path: |
            reply-with-attachments-plugin*.zip
          if-no-files-found: error
          overwrite: true
